### ISSUE TITLE
From the next page, keep a button to go back to the first page. Because when we will have some more page on application then that back button will help the user to go to previous page

### ISSUE THREAD

**Issue by satyaswarup** [dashingsat/Bridge#7]
From the next page, keep a button to go back to the first page. Because when we will have some more page on application then that back button will help the user to go to previous page

**Comment by dashingsat** [comment]
It's already there .. If we click the back arrow on the top for the add/edit rules page, control will go the landing page

**Comment by satyaswarup** [comment]
Ya , perfect
